os: windows
language: shell
env:
  global:
    secure: ttgt93XjMSydGQaiwsl8jp3y07KZGBjf0cZFDPqvhgqhD6yHOPExA/X2TDqIuKxy4uc2qiLJCGjP7nL1dmfUOMLJtDZAEF9CLynmY669zozKD//5RUVvP0JbLwIHfbhj51ZrWhN1TPZk7CSn1WOxAIpZ8h8753Xa5Xkgb1R1mJTOjAjeh8t8w8OXJhyF1huyzUSoOng54Cqna6YNkRlgzHCq+or6l2XbGQXzHb3G/IHUX5mFnXYBoC0X7IkrBMq9d1bL+Bg3tmIJZUlgascEuQFNzbAWiFZIVPKGUSq8sCZLTr8OW0HIAsuoTLc8obOMTOLZYjuMJiztYFO/tXPt2QTIgmt1qdptW9ucZAz+lTEWKCE/qXBtOP/zoHTFBnVqKSSO/lRzxahcm8bSDN40TaDamPQKwxlyPbVhkZrZwYZ6d4dOpl8MT7shB2C+LTP2VFnAlAc4zo7UCvwbI9qsENQguteN6LnuzccL2RumjQKRrp/oQCAtr4ywCFNgtu9ZLcIG/8gaiuT8nr7vqoalu/jgFM0oug123NGl62iJM7ToapuZq6KwhRbmtWwqan6P8lkeJXpGR19B7tjBGeLgncbObP2bkbNqHQWRd9YUqEUf5x0Qvn/2okrTt5nFPijW60jzOrzhw9JKJD68z42LANd6ycngEHfBtZwBKWybv+8=
script: ./test.cmd
