name: Build package
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build
      shell: cmd
      run: choco pack -v
    - name: Publish
      if: ${{ github.event_name == 'push' && github.ref == 'ref/head/master' }}
      shell: cmd
      run: |
        choco apikey --key $CHOCO_API_KEY --source https://push.chocolatey.org/
        choco push dvc*.nupkg --source https://push.chocolatey.org/
